"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:46:14.819226+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, coalesce, max as max_
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType())))
    
    # Filter NULL transaction_id and negative amounts
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    deduped_df = (transactions_df.groupBy("transaction_id")
                 .agg(max_("ingestion_timestamp").alias("latest_timestamp")))
    transactions_df = transactions_df.join(deduped_df, on=["transaction_id", "ingestion_timestamp"], how="left_semi")
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                   .option("inferSchema", "false")
                   .csv(merchants_path)
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()
    
    # Join transactions with merchants
    enriched_df = (transactions_df.join(merchants_df, on="merchant_id", how="left")
                  .withColumn("quality_flag", coalesce(col("merchant_name"), lit("UNMATCHED"))))
    
    # Write as Parquet partitioned by date
    enriched_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/bronze/transactions.csv"
    bronze_path = "s3://sigma-datatech/silver/transactions"
    merchants_path = "s3://sigma-datatech/bronze/merchants.csv"
    output_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform to Silver layer
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, avg, first, last, mode
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate total revenue and transaction count per merchant
    revenue_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(sum("amount").alias("total_revenue"), count("*").alias("txn_count"))
    
    # Calculate failure rate per merchant
    all_txns_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join revenue and failure rate calculations
    merchant_performance_df = revenue_df.join(failure_rate_df, ["merchant_id", "merchant_name", "category", "city", "date"], "left") \
        .select("merchant_id", "merchant_name", "category", "city", "date", "total_revenue", "txn_count", "failure_rate_pct")
    
    # Write output to Gold layer
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path + "/merchant_performance")

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate total spent, total transactions, and preferred payment method per customer
    ltv_df = completed_df.groupBy("customer_id") \
       .agg(sum("amount").alias("total_spent"), count("*").alias("total_txns"), avg("amount").alias("avg_txn_value"), 
             first("transaction_date").alias("first_txn_date"), last("transaction_date").alias("last_txn_date"), 
             mode("payment_method").alias("preferred_payment_method"))
    
    # Write output to Gold layer
    ltv_df.write.mode("overwrite").parquet(output_path + "/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data for the specific date
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate total revenue, total transactions, unique customers, and unique merchants
    total_revenue_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("date").agg(sum("amount").alias("total_revenue"), count("*").alias("total_txns"))
    
    unique_customers_df = silver_df.groupBy("date").agg(countDistinct("customer_id").alias("unique_customers"))
    
    unique_merchants_df = silver_df.groupBy("date").agg(countDistinct("merchant_id").alias("unique_merchants"))
    
    # Calculate failure rate
    all_txns_df = silver_df.groupBy("date").agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join all calculations
    daily_summary_df = total_revenue_df.join(unique_customers_df, "date", "inner") \
       .join(unique_merchants_df, "date", "inner") \
       .join(failure_rate_df, "date", "left") \
       .select("date", "total_revenue", "total_txns", "unique_customers", "unique_merchants", "failure_rate_pct")
    
    # Write output to Gold layer
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path + "/daily_summary")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define run metadata
    run_metadata = {"run_date": run_date, "silver_path": silver_path, "gold_output_dir": gold_output_dir}
    
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark Session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
